# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


User.destroy_all
Category.destroy_all
Card.destroy_all

sunjet = User.create(username: "SunJet", password: "password123", email: "sunjet@sunjet.com")
billy = User.create(username: "Billy", password: "password123", email: "billy@billy.com")

react = Category.create(name: "React", user_id: sunjet.id)
rails = Category.create(name: "Rails", user_id: billy.id)
japanese = Category.create(name: "Japanese", user_id: sunjet.id)
korean = Category.create(name: "Korean", user_id: billy.id)

react_1 = Card.create(term: "component", definition: "a cool tool", is_starred: false, category_id: react.id)
react_2 = Card.create(term: "props", definition: "properties for a component", is_starred: true, category_id: react.id)
rails_1 = Card.create(term: "controller", definition: "decides what's what", is_starred: false, category_id: rails.id)
rails_2 = Card.create(term: "ruby", definition: "the language", is_starred: true, category_id: rails.id)

japanese_1 = Card.create(term: "あ", definition: "a", is_starred: false, category_id: japanese.id)
japanese_2 = Card.create(term: "い", definition: "i", is_starred: false, category_id: japanese.id)
japanese_3 = Card.create(term: "う", definition: "u", is_starred: false, category_id: japanese.id)
japanese_4 = Card.create(term: "え", definition: "e", is_starred: false, category_id: japanese.id)
japanese_5 = Card.create(term: "お", definition: "o", is_starred: false, category_id: japanese.id)
japanese_6 = Card.create(term: "か", definition: "ka", is_starred: false, category_id: japanese.id)
japanese_7 = Card.create(term: "き", definition: "ki", is_starred: false, category_id: japanese.id)
japanese_8 = Card.create(term: "く", definition: "ku", is_starred: false, category_id: japanese.id)
japanese_9 = Card.create(term: "け", definition: "ke", is_starred: false, category_id: japanese.id)
japanese_10 = Card.create(term: "こ", definition: "ko", is_starred: false, category_id: japanese.id)
japanese_11 = Card.create(term: "さ", definition: "sa", is_starred: false, category_id: japanese.id)
japanese_12 = Card.create(term: "し", definition: "shi", is_starred: false, category_id: japanese.id)
japanese_13 = Card.create(term: "す", definition: "su", is_starred: false, category_id: japanese.id)
japanese_14 = Card.create(term: "せ", definition: "se", is_starred: false, category_id: japanese.id)
japanese_15 = Card.create(term: "そ", definition: "so", is_starred: false, category_id: japanese.id)
japanese_16 = Card.create(term: "た", definition: "ta", is_starred: false, category_id: japanese.id)
japanese_17 = Card.create(term: "ち", definition: "chi", is_starred: false, category_id: japanese.id)
japanese_18 = Card.create(term: "つ", definition: "tsu", is_starred: false, category_id: japanese.id)
japanese_19 = Card.create(term: "て", definition: "te", is_starred: false, category_id: japanese.id)
japanese_20 = Card.create(term: "と", definition: "to", is_starred: false, category_id: japanese.id)
japanese_21 = Card.create(term: "な", definition: "na", is_starred: false, category_id: japanese.id)
japanese_22 = Card.create(term: "に", definition: "ni", is_starred: false, category_id: japanese.id)
japanese_23 = Card.create(term: "ぬ", definition: "nu", is_starred: false, category_id: japanese.id)
japanese_24 = Card.create(term: "ね", definition: "ne", is_starred: false, category_id: japanese.id)
japanese_25 = Card.create(term: "の", definition: "no", is_starred: false, category_id: japanese.id)
japanese_26 = Card.create(term: "は", definition: "ha", is_starred: false, category_id: japanese.id)
japanese_27 = Card.create(term: "ひ", definition: "hi", is_starred: false, category_id: japanese.id)
japanese_28 = Card.create(term: "ふ", definition: "fu", is_starred: false, category_id: japanese.id)
japanese_29 = Card.create(term: "へ", definition: "he", is_starred: false, category_id: japanese.id)
japanese_30 = Card.create(term: "ほ", definition: "ho", is_starred: false, category_id: japanese.id)
japanese_31 = Card.create(term: "ま", definition: "ma", is_starred: false, category_id: japanese.id)
japanese_32 = Card.create(term: "み", definition: "mi", is_starred: false, category_id: japanese.id)
japanese_33 = Card.create(term: "む", definition: "mu", is_starred: false, category_id: japanese.id)
japanese_34 = Card.create(term: "め", definition: "me", is_starred: false, category_id: japanese.id)
japanese_35 = Card.create(term: "も", definition: "mo", is_starred: false, category_id: japanese.id)
japanese_36 = Card.create(term: "ら", definition: "ra", is_starred: false, category_id: japanese.id)
japanese_37 = Card.create(term: "り", definition: "ri", is_starred: false, category_id: japanese.id)
japanese_38 = Card.create(term: "る", definition: "ru", is_starred: false, category_id: japanese.id)
japanese_39 = Card.create(term: "れ", definition: "re", is_starred: false, category_id: japanese.id)
japanese_40 = Card.create(term: "ろ", definition: "ro", is_starred: false, category_id: japanese.id)
japanese_41 = Card.create(term: "や", definition: "ya", is_starred: false, category_id: japanese.id)
japanese_42 = Card.create(term: "ゆ", definition: "yu", is_starred: false, category_id: japanese.id)
japanese_43 = Card.create(term: "よ", definition: "yo", is_starred: false, category_id: japanese.id)
japanese_44 = Card.create(term: "わ", definition: "wa", is_starred: false, category_id: japanese.id)
japanese_45 = Card.create(term: "を", definition: "o", is_starred: false, category_id: japanese.id)
japanese_46 = Card.create(term: "ん", definition: "n", is_starred: false, category_id: japanese.id)

korean_1 = Card.create(term: "ㄱ", definition: "k", is_starred: false, category_id: korean.id)
korean_2 = Card.create(term: "ㄷ", definition: "t", is_starred: false, category_id: korean.id)
korean_3 = Card.create(term: "ㅂ", definition: "p", is_starred: false, category_id: korean.id)
korean_4 = Card.create(term: "ㅈ", definition: "ch", is_starred: false, category_id: korean.id)
korean_5 = Card.create(term: "ㅁ", definition: "m", is_starred: false, category_id: korean.id)
korean_6 = Card.create(term: "ㄴ", definition: "n", is_starred: false, category_id: korean.id)
korean_7 = Card.create(term: "ㅇ", definition: "ng", is_starred: false, category_id: korean.id)
korean_8 = Card.create(term: "ㄹ", definition: "r", is_starred: false, category_id: korean.id)
korean_9 = Card.create(term: "ㅎ", definition: "h", is_starred: false, category_id: korean.id)
korean_10 = Card.create(term: "ㅅ", definition: "s", is_starred: false, category_id: korean.id)
korean_11 = Card.create(term: "ㅋ", definition: "k", is_starred: false, category_id: korean.id)
korean_12 = Card.create(term: "ㅌ", definition: "t", is_starred: false, category_id: korean.id)
korean_13 = Card.create(term: "ㅍ", definition: "p", is_starred: false, category_id: korean.id)
korean_14 = Card.create(term: "ㅊ", definition: "ch", is_starred: false, category_id: korean.id)
korean_15 = Card.create(term: "ㅏ", definition: "a", is_starred: false, category_id: korean.id)
korean_16 = Card.create(term: "ㅓ", definition: "u", is_starred: false, category_id: korean.id)
korean_17 = Card.create(term: "ㅑ", definition: "ya", is_starred: false, category_id: korean.id)
korean_18 = Card.create(term: "ㅕ", definition: "yeo", is_starred: false, category_id: korean.id)
korean_19 = Card.create(term: "ㅣ", definition: "ee", is_starred: false, category_id: korean.id)
korean_20 = Card.create(term: "ㅐ", definition: "ae", is_starred: false, category_id: korean.id)
korean_21 = Card.create(term: "ㅔ", definition: "a", is_starred: false, category_id: korean.id)
korean_22 = Card.create(term: "ㅒ", definition: "ye", is_starred: false, category_id: korean.id)
korean_23 = Card.create(term: "ㅖ", definition: "yay", is_starred: false, category_id: korean.id)
korean_24 = Card.create(term: "ㅗ", definition: "o", is_starred: false, category_id: korean.id)
korean_25 = Card.create(term: "ㅜ", definition: "u", is_starred: false, category_id: korean.id)
korean_26 = Card.create(term: "ㅛ", definition: "yo", is_starred: false, category_id: korean.id)
korean_27 = Card.create(term: "ㅠ", definition: "yu", is_starred: false, category_id: korean.id)
korean_28 = Card.create(term: "ㅡ", definition: "eu", is_starred: false, category_id: korean.id)
korean_29 = Card.create(term: "ㅘ", definition: "wa", is_starred: false, category_id: korean.id)
korean_30 = Card.create(term: "ㅝ", definition: "wo", is_starred: false, category_id: korean.id)
korean_31 = Card.create(term: "ㅙ", definition: "wae", is_starred: false, category_id: korean.id)
korean_32 = Card.create(term: "ㅟ", definition: "wii", is_starred: false, category_id: korean.id)
korean_33 = Card.create(term: "ㅢ", definition: "we", is_starred: false, category_id: korean.id)
korean_34 = Card.create(term: "ㄲ", definition: "kk", is_starred: false, category_id: korean.id)
korean_35 = Card.create(term: "ㅃ", definition: "pp", is_starred: false, category_id: korean.id)
korean_36 = Card.create(term: "ㅉ", definition: "jj", is_starred: false, category_id: korean.id)
korean_37 = Card.create(term: "ㄸ", definition: "tt", is_starred: false, category_id: korean.id)
korean_38 = Card.create(term: "ㅆ", definition: "ss", is_starred: false, category_id: korean.id)
korean_39 = Card.create(term: "ㅞ", definition: "we", is_starred: false, category_id: korean.id)
korean_40 = Card.create(term: "ㅚ", definition: "oe", is_starred: false, category_id: korean.id)
